name: Build and deploy JAR app to Azure Web App - camp-backend
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: Backend
        run: mvn clean package -DskipTests -Dmaven.test.skip=true -Dmaven.compiler.testExcludes="**/*"
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: Backend/target/backend-0.0.1-SNAPSHOT.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EF17F6049C8A41A7A357C7DC6FC79E4C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_51CF5BCB8EE440CC8EEC1E8BE160C9CD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_131050BC95D048BE99D8A01EAD47B648 }}
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'camp-backend'
          slot-name: 'Production'
          package: backend-0.0.1-SNAPSHOT.jar
